---
_extends: .github

repository:
  name: toxins
  description: A collection of small programs using toxcore.
  topics: toxcore

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "bazel-opt"
          - "Codacy Static Code Analysis"
          - "code-review/reviewable"
