---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.31-release
    cpu: 2
    memory: 6G
  configure_script:
    - git submodule update --init --depth=10 --recursive
    - /src/workspace/tools/inject-repo toxins
  test_all_script:
    - cd /src/workspace && bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        //toxins/...
